In [1]:
import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/MyungKyuYi/AI-class/refs/heads/main/heart.csv")
df

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0     63    1   3       145   233    1        0      150      0      2.3   
1     37    1   2       130   250    0        1      187      0      3.5   
2     41    0   1       130   204    0        0      172      0      1.4   
3     56    1   1       120   236    0        1      178      0      0.8   
4     57    0   0       120   354    0        1      163      1      0.6   
..   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
298   57    0   0       140   241    0        1      123      1      0.2   
299   45    1   3       110   264    0        1      132      0      1.2   
300   68    1   0       144   193    1        1      141      0      3.4   
301   57    1   0       130   131    0        1      115      1      1.2   
302   57    0   1       130   236    0        0      174      0      0.0   

     slope  ca  thal  target  
0        0   0     1       1  
1        0   0     2       1  
2        2   0     2       1  
3        2   0     2       1  
4        2   0     2       1  
..     ...  ..   ...     ...  
298      1   0     3       0  
299      1   0     3       0  
300      1   2     3       0  
301      1   1     3       0  
302      1   1     2       0  

[303 rows x 14 columns]

In [2]:
#결측치 확인
df.isnull().sum()

age         0
sex         0
cp          0
trestbps    0
chol        0
fbs         0
restecg     0
thalach     0
exang       0
oldpeak     0
slope       0
ca          0
thal        0
target      0
dtype: int64

In [3]:
#원-핫 인코딩 (thal, restecg, cp)
columns_to_encode = ["thal", "restecg", "cp", "thal"]
df=pd.get_dummies(df, columns=columns_to_encode)
df

age  sex  trestbps  chol  fbs  thalach  exang  oldpeak  slope  ca  ...  \
0     63    1       145   233    1      150      0      2.3      0   0  ...   
1     37    1       130   250    0      187      0      3.5      0   0  ...   
2     41    0       130   204    0      172      0      1.4      2   0  ...   
3     56    1       120   236    0      178      0      0.8      2   0  ...   
4     57    0       120   354    0      163      1      0.6      2   0  ...   
..   ...  ...       ...   ...  ...      ...    ...      ...    ...  ..  ...   
298   57    0       140   241    0      123      1      0.2      1   0  ...   
299   45    1       110   264    0      132      0      1.2      1   0  ...   
300   68    1       144   193    1      141      0      3.4      1   2  ...   
301   57    1       130   131    0      115      1      1.2      1   1  ...   
302   57    0       130   236    0      174      0      0.0      1   1  ...   

     restecg_1  restecg_2   cp_0   cp_1   cp_2   cp_3  thal_0  thal_1  thal_2  \
0        False      False  False  False  False   True   False    True   False   
1         True      False  False  False   True  False   False   False    True   
2        False      False  False   True  False  False   False   False    True   
3         True      False  False   True  False  False   False   False    True   
4         True      False   True  False  False  False   False   False    True   
..         ...        ...    ...    ...    ...    ...     ...     ...     ...   
298       True      False   True  False  False  False   False   False   False   
299       True      False  False  False  False   True   False   False   False   
300       True      False   True  False  False  False   False   False   False   
301       True      False   True  False  False  False   False   False   False   
302      False      False  False   True  False  False   False   False    True   

     thal_3  
0     False  
1     False  
2     False  
3     False  
4     False  
..      ...  
298    True  
299    True  
300    True  
301    True  
302   False  

[303 rows x 26 columns]

In [4]:
# 라벨 특성 분류
x=df.drop("target",axis=1)
y=df["target"]
print(x.shape)
print(y.shape)

(303, 25)
(303,)


In [5]:
# csv → array
#라벨 확인
import numpy as np
x=x.to_numpy().astype(float)
y=y.to_numpy()
print(x)
print(y)

[[ 63.   1. 145. ...   1.   0.   0.]
 [ 37.   1. 130. ...   0.   1.   0.]
 [ 41.   0. 130. ...   0.   1.   0.]
 ...
 [ 68.   1. 144. ...   0.   0.   1.]
 [ 57.   1. 130. ...   0.   0.   1.]
 [ 57.   0. 130. ...   0.   1.   0.]]
[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0]


In [6]:
# train_test 분류
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y)
print(x_train.shape, x_test.shape)
print(y_train.shape, y_test.shape)

(227, 25) (76, 25)
(227,) (76,)


In [7]:
# 하이퍼 파라미터 튜닝

from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD,Adam


model = Sequential()

model.add(Dense(25,input_shape=(25,),activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(20,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(10,activation='relu'))
model.add(Dense(5,activation='relu'))
model.add(Dense(5,activation='relu'))
model.add(Dense(1,activation='sigmoid'))

model.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model.summary()

C:\Users\김찬희\AppData\Roaming\Python\Python312\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 25)                  │             650 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 20)                  │             520 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 20)                  │             420 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_3 (Dense)                      │ (None, 10)                  │             210 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_4 (Dense)                      │ (None, 10)                  │             110 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_5 (Dense)                      │ (None, 5)                   │              55 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_6 (Dense)                      │ (None, 5)                   │              30 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_7 (Dense)                      │ (None, 1)                   │               6 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 2,001 (7.82 KB)

 Trainable params: 2,001 (7.82 KB)

 Non-trainable params: 0 (0.00 B)

In [8]:
# 학습, 테스트
dep=model.fit(x=x_train,y=y_train, epochs=20)

test_loss, test_acc = model.evaluate(x_test, y_test)

print("loss :",test_loss)
print("accuracy :",test_acc)

Epoch 1/20


C:\Users\김찬희\AppData\Roaming\Python\Python312\site-packages\keras\src\losses\losses.py:33: SyntaxWarning: In loss categorical_crossentropy, expected y_pred.shape to be (batch_size, num_classes) with num_classes > 1. Received: y_pred.shape=(None, 1). Consider using 'binary_crossentropy' if you only have 2 classes.
  return self.fn(y_true, y_pred, **self._fn_kwargs)


8/8 ━━━━━━━━━━━━━━━━━━━━ 6s 15ms/step - accuracy: 0.3952 - loss: 0.0000e+00
Epoch 2/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4626 - loss: 0.0000e+00
Epoch 3/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4043 - loss: 0.0000e+00
Epoch 4/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3977 - loss: 0.0000e+00
Epoch 5/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4045 - loss: 0.0000e+00
Epoch 6/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4551 - loss: 0.0000e+00
Epoch 7/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.3998 - loss: 0.0000e+00
Epoch 8/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.4405 - loss: 0.0000e+00
Epoch 9/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.4002 - loss: 0.0000e+00
Epoch 10/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4366 - loss: 0.0000e+00
Epoch 11/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.4178 - loss: 0.0000e+00
Epoch 12/20
8/8 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - 